[package]
name = "ui"
version.workspace = true
edition.workspace = true

[dependencies]
gpui.workspace = true
gpui-component.workspace = true
gpui-component-assets.workspace = true
theme.workspace = true
rust-embed.workspace = true
