[package]
name = "connection"
version.workspace = true
edition.workspace = true

[dependencies]
gpui.workspace = true
gpui-component.workspace = true
theme.workspace = true
ui.workspace = true
open.workspace = true
