[package]
name = "theme"
version.workspace = true
edition.workspace = true

[dependencies]
gpui.workspace = true
gpui-component.workspace = true
rust-embed.workspace = true
tracing.workspace = true
directories.workspace = true
